### ISSUE TITLE
Profile don't exist

### ISSUE THREAD

**Issue by vsppedro** [CommandrAvander/elasticsearch-django-tutorial#2]
Hello,

I was trying to make this tutorial, I was in this part "django-admin startproject project --template=https://github.com/ambivalento/django-skeleton/archive/master.zip". 

The strange thing is, when I try to acess "https://github.com/ambivalento/", I got '404'.

Why this profile don't exist? Ambivalent is the profile that should contain django-skeleton/archive/master.zip.

**Comment by ambivalentno** [comment]
there's a typo. Actually, the profile is https://github.com/ambivalentno/

**Comment by vsppedro** [comment]
My bad! Thank you!
